language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: <YOUR ENCRYPTED KEY HERE>
  app: agile-cove-70530
  on:
    repo: https://github.com/wannab3d3v3lop3r/mood-project